### ISSUE TITLE
server socket error when ssh client don't trust server's pubkey

### ISSUE THREAD

**Issue by laixintao** [laixintao/lobbyboy#19]
```DEB [20211125-11:06:13.766] thr=123145464999936 paramiko.transport:1819: Kex agreed: curve25519-sha256@libssh.org
DEB [20211125-11:06:13.766] thr=123145464999936 paramiko.transport:1819: HostKey agreed: ssh-rsa
DEB [20211125-11:06:13.766] thr=123145464999936 paramiko.transport:1819: Cipher agreed: aes128-ctr
DEB [20211125-11:06:13.766] thr=123145464999936 paramiko.transport:1819: MAC agreed: hmac-sha2-256-etm@openssh.com
DEB [20211125-11:06:13.766] thr=123145464999936 paramiko.transport:1819: Compression agreed: none
DEB [20211125-11:06:13.773] thr=123145464999936 paramiko.transport:1819: kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
DEB [20211125-11:06:13.775] thr=123145464999936 paramiko.transport:1819: EOF in transport thread
CRI [20211125-11:06:13.775] thr=123145448210432 lobbyboy.socket_handle:248: *** Socket thread error.
Traceback (most recent call last):
  File "/Users/xintao.lai/Programs/lobbyboy/lobbyboy/socket_handle.py", line 229, in run
    server = self.prepare_server(t)
  File "/Users/xintao.lai/Programs/lobbyboy/lobbyboy/socket_handle.py", line 135, in prepare_server
    t.start_server(server=server)
  File "/Users/xintao.lai/Library/Caches/pypoetry/virtualenvs/lobbyboy-2mvenFOp-py3.9/lib/python3.9/site-packages/paramiko/transport.py", line 728, in start_server
    raise e
  File "/Users/xintao.lai/Library/Caches/pypoetry/virtualenvs/lobbyboy-2mvenFOp-py3.9/lib/python3.9/site-packages/paramiko/transport.py", line 2055, in run
    ptype, m = self.packetizer.read_message()
  File "/Users/xintao.lai/Library/Caches/pypoetry/virtualenvs/lobbyboy-2mvenFOp-py3.9/lib/python3.9/site-packages/paramiko/packet.py", line 459, in read_message
    header = self.read_all(self.__block_size_in, check_rekey=True)
  File "/Users/xintao.lai/Library/Caches/pypoetry/virtualenvs/lobbyboy-2mvenFOp-py3.9/lib/python3.9/site-packages/paramiko/packet.py", line 303, in read_all
    raise EOFError()
EOFError
```

**Comment by laixintao** [comment]
```
Please contact your system administrator.
Add correct host key in /Users/xintao.lai/.ssh/known_hosts to get rid of this message.
Offending RSA key in /Users/xintao.lai/.ssh/known_hosts:1498
RSA host key for [127.0.0.1]:12200 has changed and you have requested strict checking.
Host key verification failed.
```
